/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunasRouteImport } from './routes/runas'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcercaRouteImport } from './routes/acerca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OraculoIndexRouteImport } from './routes/oraculo.index'
import { Route as PagoPendienteRouteImport } from './routes/pago.pendiente'
import { Route as PagoExitoRouteImport } from './routes/pago.exito'
import { Route as PagoErrorRouteImport } from './routes/pago.error'
import { Route as OraculoTypeRouteImport } from './routes/oraculo.$type'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago.webhook'

const RunasRoute = RunasRouteImport.update({
  id: '/runas',
  path: '/runas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaRoute = AcercaRouteImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OraculoIndexRoute = OraculoIndexRouteImport.update({
  id: '/oraculo/',
  path: '/oraculo/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoPendienteRoute = PagoPendienteRouteImport.update({
  id: '/pago/pendiente',
  path: '/pago/pendiente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoExitoRoute = PagoExitoRouteImport.update({
  id: '/pago/exito',
  path: '/pago/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoErrorRoute = PagoErrorRouteImport.update({
  id: '/pago/error',
  path: '/pago/error',
  getParentRoute: () => rootRouteImport,
} as any)
const OraculoTypeRoute = OraculoTypeRouteImport.update({
  id: '/oraculo/$type',
  path: '/oraculo/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/auth': typeof AuthRoute
  '/historial': typeof HistorialRoute
  '/runas': typeof RunasRoute
  '/oraculo/$type': typeof OraculoTypeRoute
  '/pago/error': typeof PagoErrorRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/oraculo/': typeof OraculoIndexRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/auth': typeof AuthRoute
  '/historial': typeof HistorialRoute
  '/runas': typeof RunasRoute
  '/oraculo/$type': typeof OraculoTypeRoute
  '/pago/error': typeof PagoErrorRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/oraculo': typeof OraculoIndexRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/auth': typeof AuthRoute
  '/historial': typeof HistorialRoute
  '/runas': typeof RunasRoute
  '/oraculo/$type': typeof OraculoTypeRoute
  '/pago/error': typeof PagoErrorRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/oraculo/': typeof OraculoIndexRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca'
    | '/auth'
    | '/historial'
    | '/runas'
    | '/oraculo/$type'
    | '/pago/error'
    | '/pago/exito'
    | '/pago/pendiente'
    | '/oraculo/'
    | '/api/public/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca'
    | '/auth'
    | '/historial'
    | '/runas'
    | '/oraculo/$type'
    | '/pago/error'
    | '/pago/exito'
    | '/pago/pendiente'
    | '/oraculo'
    | '/api/public/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/acerca'
    | '/auth'
    | '/historial'
    | '/runas'
    | '/oraculo/$type'
    | '/pago/error'
    | '/pago/exito'
    | '/pago/pendiente'
    | '/oraculo/'
    | '/api/public/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaRoute: typeof AcercaRoute
  AuthRoute: typeof AuthRoute
  HistorialRoute: typeof HistorialRoute
  RunasRoute: typeof RunasRoute
  OraculoTypeRoute: typeof OraculoTypeRoute
  PagoErrorRoute: typeof PagoErrorRoute
  PagoExitoRoute: typeof PagoExitoRoute
  PagoPendienteRoute: typeof PagoPendienteRoute
  OraculoIndexRoute: typeof OraculoIndexRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runas': {
      id: '/runas'
      path: '/runas'
      fullPath: '/runas'
      preLoaderRoute: typeof RunasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oraculo/': {
      id: '/oraculo/'
      path: '/oraculo'
      fullPath: '/oraculo/'
      preLoaderRoute: typeof OraculoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/pendiente': {
      id: '/pago/pendiente'
      path: '/pago/pendiente'
      fullPath: '/pago/pendiente'
      preLoaderRoute: typeof PagoPendienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/exito': {
      id: '/pago/exito'
      path: '/pago/exito'
      fullPath: '/pago/exito'
      preLoaderRoute: typeof PagoExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/error': {
      id: '/pago/error'
      path: '/pago/error'
      fullPath: '/pago/error'
      preLoaderRoute: typeof PagoErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oraculo/$type': {
      id: '/oraculo/$type'
      path: '/oraculo/$type'
      fullPath: '/oraculo/$type'
      preLoaderRoute: typeof OraculoTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaRoute: AcercaRoute,
  AuthRoute: AuthRoute,
  HistorialRoute: HistorialRoute,
  RunasRoute: RunasRoute,
  OraculoTypeRoute: OraculoTypeRoute,
  PagoErrorRoute: PagoErrorRoute,
  PagoExitoRoute: PagoExitoRoute,
  PagoPendienteRoute: PagoPendienteRoute,
  OraculoIndexRoute: OraculoIndexRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
